require('TcoreR.plugin_conf.comment')
require('TcoreR.plugin_conf.fugitive')
require('TcoreR.plugin_conf.harpoon')
require('TcoreR.plugin_conf.lsp')
require('TcoreR.plugin_conf.rose-pine')
require('TcoreR.plugin_conf.telescope')
require('TcoreR.plugin_conf.treesitter')
require('TcoreR.plugin_conf.undotree')
